### ISSUE TITLE
Help to add wm8960 codec on up squared

### ISSUE THREAD

**Issue by nicola-lunghi** [plbossart/MinnowBoardMaxFirmware#2]
Hi,
I'm looking for some information about how to add the wm8960 codec (+sof) to the up squared board.

In particular I have no idea how to find the acpi _hid for that codec. There's a list somewhere?
Or I need to use the special "PRP0001" id?
After that should be pretty similar to the WM8731 asl file i imagine.
Thanks
Nick

**Comment by nicola-lunghi** [comment]
The hat is this

https://www.waveshare.com/wiki/WM8960_Audio_HAT

Dr overlay for rpi

https://github.com/raspberrypi/linux/pull/4039/commits/d49093bd0a5cf40e0994c23382ac411f82debe22

**Comment by plbossart** [comment]
Hi @nicola-lunghi good to hear from you.

I am afraid the existing code in sound/soc/codecs/wm8960.c does not support ACPI. It's not difficult to add, you can e.g. look how I did it in wm8804.c for the HifiBerry Digiplus HAT.

````c
#ifdef CONFIG_ACPI
static const struct acpi_device_id wm8960_acpi_match[] = {
	{ "1AEC8960", 0 }, /* Wolfson PCI ID + part ID */
	{ },
};
MODULE_DEVICE_TABLE(acpi, wm8960_acpi_match);
#endif
````

and then you would use the same '1AEC8960' in a table, but this is the wrong repository. You would need to look at https://github.com/thesofproject/acpi-scripts/tree/master/Up2 and then copy an existing .asl file and replace the codec name by the WM8960 one.

**Comment by nicola-lunghi** [comment]
Hi @plbossart good to talk to you too!
(I'm still playing with the up2 on my free time every now and then) 
I've sent a patch to add the acpi to the wm8960 codec and this weekend I'll try it better on the up2 to see if I need to setup anything else

Thank you
Nick

**Comment by plbossart** [comment]
@nicola-lunghi do you know where this HAT can be purchased? we've only used HifiBerry cards so far, it'd be good to add new ones.

**Comment by nicola-lunghi** [comment]
I got it from the pi hut in the uk

https://thepihut.com/products/hi-fi-sound-card-
<https://thepihut.com/products/hi-fi-sound-card-hat-for-raspberry-pi-with-speakers>
hat-for-raspberry-pi-with-speakers
<https://thepihut.com/products/hi-fi-sound-card-hat-for-raspberry-pi-with-speakers>

They have a lot of other audio hat for rpi

https://thepihut.com/collections/raspberry-pi-audio-hats


Cheers,
Nicola

**Comment by plbossart** [comment]
Thanks @nicola-lunghi, I ordered two different boards based on that codec. We can add a machine driver for it, that should be easy.
